# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f6eeb916eaa2f92a06148f28069f524d55de54b1e162c08b00c089c0a3bac5e4a05e1c23e08b6f16018aafc5ca1ab9b46e50332f0d69553ebc3b4ebd670f17b

test:
  secret_key_base: 4c234be7df40a94ecd4a9473012a4ac61dc679981aa33389b3ad1c1020b774fb3bdfc577faf67a66b1029e30ac9946ff058937dcafaf0f0177c724ca0c7046f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
